OnlineShop2025/Controllers/CartController.cs
using System;
using System.Security.Claims;
using Asp2025_DataAccess.Data;
using Asp2025_DataAccess.Repository;
using Asp2025_DataAccess.Repository.IRepository;
using Asp2025_Models;
using Asp2025_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using OnlineShop.Utility;

namespace OnlineShop.Controllers;

public class CartController : Controller
{
    private IProductRepository productRepository;
    private IInquiryDetailRepository inquiryDetailRepository;
    private IInquiryHeaderRepository inquiryHeaderRepository;

    public CartController(ApplicationDbContext context, IProductRepository productRepository, IInquiryDetailRepository inquiryDetailRepository, IInquiryHeaderRepository inquiryHeaderRepository)
    {
        this.productRepository = productRepository;
        this.inquiryDetailRepository = inquiryDetailRepository;
        this.inquiryHeaderRepository = inquiryHeaderRepository;

    }

    [HttpPost]
    [ActionName("Index")]
    public IActionResult IndexPost(IEnumerable<Product> products)
    {
        List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();

        foreach (var prod in products)
        {
            shoppingCarts.Add(new ShoppingCart()
            {
                ProductId = prod.Id,
                Count = prod.TempCount
            });
        }

        HttpContext.Session.Set(WC.SessionCart, shoppingCarts);

        return RedirectToAction("Summary");
    }

    public IActionResult Summary()
    {
        var claimIdentity = (ClaimsIdentity)User.Identity;

        // если пользователь зашел в систему он будет точно определен
        var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

        // достаем инфу и вбрасываем ее в поля

        return null;
    }

    public IActionResult Index()
    {
        List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();
        if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null &&
       HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
        {
            shoppingCarts = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }
        else
        {
            return View();
        }
        // DetailsVM detailsVM = new DetailsVM()
        // {
        //     Product = context.Product.Include(p => p.Category).Include(p => p.Company).Where(p => p.Id == id).FirstOrDefault(),
        //     ExistsInCart = false
        // };
        List<Product> productsInCart = new List<Product>();
        var products = productRepository.GetAll(includeProperties: "Category,Company");

        foreach (var item in shoppingCarts)
        {
            var prod = products.FirstOrDefault(x => x.Id == item.ProductId);

            prod.TempCount = item.Count;    // ???

            productsInCart.Add(prod);
        }
        return View(productsInCart);
    }

    [HttpPost]
    public IActionResult UpdateCart(List<Product> products)
    {
        List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();

        foreach (var prod in products)
        {
            shoppingCarts.Add(new ShoppingCart()
            {
                ProductId = prod.Id,
                Count = prod.TempCount
            });
        }

        HttpContext.Session.Set(WC.SessionCart, shoppingCarts);

        return RedirectToAction("Index");
    }

    [HttpPost]
    [Authorize]
    public IActionResult InquiryAdd(string fullName, string phone, string email)
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);


        InquiryHeader inquiryHeader = new InquiryHeader()
        {

            FullName = fullName,
            PhoneNumber = phone,
            Email = email,
            InquiryDate = DateTime.Now,
            ApplicationUserId = claim.Value,
        };
        inquiryHeaderRepository.Add(inquiryHeader);
        inquiryHeaderRepository.Save();

        List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();
        if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null &&
       HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
        {
            shoppingCarts = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }
        else
        {
            TempData[WC.Error] = "No products in cart";
            return View();
        }

        foreach (var item in shoppingCarts)
        {
            InquiryDetail inquiryDetail = new InquiryDetail()
            {
                ProductId = item.ProductId,
                InquiryHeaderId = inquiryHeader.Id,
                Count = item.Count // Assuming Count is the quantity of the product
            };
            inquiryDetailRepository.Add(inquiryDetail);
        }
        inquiryDetailRepository.Save();
        TempData[WC.Success] = "Inquiry created successfully";
        return RedirectToAction("Index", "Home");
    }

}


OnlineShop2025/Controllers/CompanyController.cs
using Asp2025_DataAccess.Data;
using Asp2025_Models;
using Asp2025_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Utility;

using Asp2025_DataAccess.Repository.IRepository;
using Asp2025_DataAccess.Repository;

namespace OnlineShop.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CompanyController : Controller
    {

        private ICompanyRepository companyRepository;
        public CompanyController(ICompanyRepository companyRepository)
        {
            this.companyRepository = companyRepository;
        }


        // GET: CompanyController
        public ActionResult Index()
        {
            return View(companyRepository.GetAll());
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(string name)
        {

            Company company1 = new Company()
            {
                Name = name
            };
            companyRepository.Add(company1);
            companyRepository.Save();
            TempData[WC.Success] = "Company created successfully";
            return RedirectToAction("Index", companyRepository.GetAll());
        }

        public IActionResult Edit(int id)
        {
            var comp = companyRepository.Find(id);
            
            return View(comp);
        }
        [HttpPost]
        public IActionResult Edit(Company company)
        {
            if (ModelState.IsValid)
            {
                companyRepository.Update(company);
                companyRepository.Save();
                TempData[WC.Success] = "Company created successfully";
                return RedirectToAction("Index");
            }
            return View(company);
        }

        public IActionResult Delete(int id)
        {
            var comp = companyRepository.Find(id);
            companyRepository.Remove(comp);
            companyRepository.Save();
            TempData[WC.Success] = "Company deleted successfully";
            return RedirectToAction("Index");
        }

    }
}

OnlineShop2025/Controllers/InquiryController.cs
using Asp2025_DataAccess.Repository;
using Asp2025_DataAccess.Repository.IRepository;
using Asp2025_Models;
using Asp2025_Models.ViewModel;
using Asp2025_Utility;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShop.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class InquiryController : Controller
    {
        private IInquiryHeaderRepository headerRepository;
        private IInquiryDetailRepository detailRepository;

        [BindProperty]
        public InquiryVM inquiryVM { get; set; }

        public InquiryController(IInquiryHeaderRepository headerRepository, IInquiryDetailRepository detailRepository)
        {
            this.headerRepository = headerRepository;
            this.detailRepository = detailRepository;
        }
        // GET: InquiryController
        public ActionResult Index()
        {
            return View();
        }

        

        public IActionResult Details(int id)
        {
            InquiryVM inquiryVM = new InquiryVM()
            {
                InquiryHeader = headerRepository.FirstOrDefault(x => x.Id == id),
                InquiryDetails = detailRepository.GetAll(x => x.InquiryHeaderId == id, includeProperties: "Product")
            };
            return View(inquiryVM);
        }

        [HttpPost]
        public IActionResult Delete()
        {
            InquiryHeader inquiryHeader = headerRepository.FirstOrDefault(x => x.Id == inquiryVM.InquiryHeader.Id);
            IEnumerable<InquiryDetail> inquiryDetails = detailRepository.GetAll(x => x.InquiryHeaderId == inquiryVM.InquiryHeader.Id);

            detailRepository.RemoveRange(inquiryDetails);
            headerRepository.Remove(inquiryHeader);
            headerRepository.Save();
            TempData[WC.Success] = "Inquiry deleted successfully";  
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetInquiryList()
        {
            var inquiryList = headerRepository.GetAll();
            return Json(new { data = inquiryList });
        }

    }
}

OnlineShop2025/Controllers/OrderController.cs
using System.Security.Claims;
using Asp2025_DataAccess.Repository.IRepository;
using Asp2025_Models;
using Asp2025_Models.ViewModel;
using Asp2025_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace OnlineShop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private IOrderHeaderRepository orderHeaderRepository;
        private IOrderDetailRepository orderDetailRepository;
        private IInquiryDetailRepository inquiryDetailRepository;
        private IInquiryHeaderRepository inquiryHeaderRepository;
        public OrderController(IOrderHeaderRepository orderHeaderRepository, IOrderDetailRepository orderDetailRepository, IInquiryDetailRepository inquiryDetailRepository, IInquiryHeaderRepository inquiryHeaderRepository)
        {
            this.orderHeaderRepository = orderHeaderRepository;
            this.orderDetailRepository = orderDetailRepository;
            this.inquiryDetailRepository = inquiryDetailRepository;
            this.inquiryHeaderRepository = inquiryHeaderRepository;
        }
        // GET: OrderController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetOrderListUser()
        {
            if (User.IsInRole(WC.AdminRole))
            {
                return RedirectToAction("GetOrderList");
            }
            var inquiryList = orderHeaderRepository.GetAll(filter: x => x.CreateByUserId == User.FindFirst(ClaimTypes.NameIdentifier).Value).Select(x => new
            {
                Id = x.Id,
                OrderDate = x.OrdereDate.ToString("dd.MM.yyyy"),
                OrderStatus = x.OrderStatus,
                FinalOrderTotal = x.FinalOrderTotal,
            });

            if (inquiryList == null)
            {
                return NotFound();
            }
            return Json(new { data = inquiryList });
        }
        [HttpGet]
        public IActionResult GetOrderList()
        {
            var orderList = orderHeaderRepository.GetAll().Select(x => new
            {
                Id = x.Id,
                OrderDate = x.OrdereDate.ToString("dd.MM.yyyy"),
                OrderStatus = x.OrderStatus,
                FinalOrderTotal = x.FinalOrderTotal,
            });
            return Json(new { data = orderList });
        }
        public IActionResult AddOrder(InquiryVM inquiryVM)
        {
            inquiryVM.InquiryDetails = inquiryDetailRepository.GetAll(x => x.InquiryHeaderId == inquiryVM.InquiryHeader.Id, includeProperties: "Product");
            var products = inquiryVM.InquiryDetails.Select(x => x.Product).ToList();
            var total = products.Sum(x => x.Price * x.TempCount);

            OrderHeader orderHeader = new OrderHeader()
            {
                CreateByUserId = inquiryVM.InquiryHeader.ApplicationUserId,
                OrdereDate = DateTime.Now,
                ShippedDate = DateTime.Now.AddDays(7),
                FinalOrderTotal = total,
                OrderStatus = WC.StatusApproved,
                PaymentDate = DateTime.Now,
                PhoneNumber = inquiryVM.InquiryHeader.PhoneNumber,
                Email = inquiryVM.InquiryHeader.Email,
                FullName = inquiryVM.InquiryHeader.FullName,
            };

            orderHeaderRepository.Add(orderHeader);
            orderHeaderRepository.Save();
            foreach (var item in inquiryVM.InquiryDetails)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderHeaderId = orderHeader.Id,
                    ProductId = item.ProductId,
                    Count = item.Count,
                    PricePer = item.Product.Price
                };
                orderDetailRepository.Add(orderDetail);
                orderDetailRepository.Save();
            }
            inquiryDetailRepository.RemoveRange(inquiryVM.InquiryDetails);
            inquiryHeaderRepository.Remove(inquiryVM.InquiryHeader);
            inquiryHeaderRepository.Save();
            return RedirectToAction("Index");
        }



        public IActionResult Details(int id)
        {
            OrderVM orderVM = new OrderVM()
            {
                OrderHeader = orderHeaderRepository.FirstOrDefault(x => x.Id == id),
                OrderDetails = orderDetailRepository.GetAll(x => x.OrderHeaderId == id, includeProperties: "Product")
            };
            return View(orderVM);
        }

        public IActionResult ChangeStatusOrder(int orderId)
        {
            var order = orderHeaderRepository.FirstOrDefault(x => x.Id == orderId);
            if (order == null)
            {
                return NotFound("Order not found");
            }
            if (order.OrderStatus == WC.StatusCompleted)
            {
                DeleteOrder(order);
                return RedirectToAction("Index");
            }

            var statusIndex = Array.IndexOf(WC.OrderStatusList, order.OrderStatus);
            order.OrderStatus = WC.OrderStatusList[statusIndex + 1];
            orderHeaderRepository.Update(order);
            orderHeaderRepository.Save();

            return RedirectToAction("Details", new { id = orderId });
        }

        private void DeleteOrder(OrderHeader order)
        {
            IEnumerable<OrderDetail> orderDetails = orderDetailRepository.GetAll(x => x.OrderHeaderId == order.Id);
            orderDetailRepository.RemoveRange(orderDetails);
            orderHeaderRepository.Remove(order);
            orderHeaderRepository.Save();
            TempData[WC.Error] = "Order deleted successfully";


        }
    }
}

OnlineShop2025/Views/Shared/_Layout.cshtml
@using Asp2025_Models
@using Asp2025_Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
@using OnlineShop.Utility
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.3.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product"
                                asp-action="Index">Product</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order"
                                asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            @if (httpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) !=
                                                        null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count =
                                        httpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a class="nav-link">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(0)
                                </a>
                            }
                        </li>
                        @if (User.IsInRole(WC.AdminRole))
                        {
                            <li class="nav-item">
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                        Content Manager
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                        <li><a class="dropdown-item" asp-action="Index"
                                                asp-controller="Category">Category</a>
                                        </li>
                                        <li> <a class="nav-link text-dark dropdown-item" asp-area=""
                                                asp-controller="Company" asp-action="Index">Company</a></li>
                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item" style="margin-left: 10px;">
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                        Order Manager
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                        <li><a class="dropdown-item" asp-action="Index" asp-controller="Inquiry">Inquiry</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create Admin
                                    User</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.3.0/js/dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

OnlineShop2025/Views/Shared/_Notifications.cshtml
@using Asp2025_Utility

@if (TempData[WC.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData[WC.Success]');
    </script>
}

@if (TempData[WC.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData[WC.Error]');
    </script>
}